/*
 * Exercise 16 — Capstone: Refactor Java to Kotlin
 * =================================================
 *
 * KEY CONCEPTS:
 *   Nothing new — this is a victory lap. This time you don't start from a blank stub:
 *   you start from ~250 lines of real, working, compiling Java right next door in
 *
 *       src/main/kotlin/ex16/legacy/
 *
 *   (Customer, LineItem, Order, the Payment hierarchy, and OrderUtils). Read it first.
 *   Every problem site is annotated in place with DANGER or CLUTTER comments, and
 *   LegacyJavaTest in src/test/kotlin/ex16/ PASSES from the start — its green tests are
 *   the bug reports: the NPE the compiler never warned about, the discount that
 *   corrupts the order for everyone else, the getter that leaks the internal list.
 *
 *   Money is BigDecimal throughout — never Double. In Java that turns every price
 *   formula into a .multiply(...).divide(...) chain; Kotlin's stdlib overloads the
 *   arithmetic operators for BigDecimal, so the same type reads like arithmetic here.
 *   (Bonus: Kotlin's BigDecimal `/` defaults to HALF_EVEN rounding, where Java's bare
 *   divide() throws ArithmeticException the day a quotient stops terminating.)
 *
 *   Your job: port the legacy program to the Kotlin below and make CapstoneTest pass.
 *   The data model is already ported (4 lines, right below — compare with the three
 *   POJO files). The functions are yours.
 *
 * JAVA ANALOGY — the port map (legacy construct → Kotlin feature → exercise):
 *
 *   Customer/LineItem/Order POJOs, ~150 lines     →  data class, 3 lines           (ex04)
 *   telescoping constructors                      →  default values in the ctor    (ex06)
 *   setters + leaked mutable List                 →  val + read-only List          (ex01, ex04)
 *   hand-rolled equals/hashCode/toString          →  generated by `data`           (ex04)
 *   "may be null" Javadoc on getEmail()           →  String? + ?. + let + ?:       (ex03, ex13)
 *   OrderUtils static utility class               →  top-level & extension funs    (ex07)
 *   price.multiply(...).divide(...) chains        →  BigDecimal * and / operators  (stdlib)
 *   compareTo(minimum) >= 0                       →  just >=                       (stdlib)
 *   grandTotal accumulator loop                   →  items.sumOf { }               (ex08, ex09)
 *   instanceof chain + casts + else-throw         →  sealed class + when           (ex11, ex05)
 *   Pending.INSTANCE singleton ritual             →  object Pending                (ex12)
 *   receipt() overloads ×3 + StringBuilder loop   →  defaults + templates
 *                                                    + joinToString { }            (ex02, ex06, ex08)
 *   stream().collect(groupingBy(reducing(...)))   →  groupBy + filter + sorted     (ex09, ex14)
 *   void applyDiscount() in-place mutation        →  copy() — a new order,
 *                                                    original untouched            (ex04)
 *
 *   Scorecard: the Java program is ~250 lines with six labelled landmines, all of which
 *   compile without a warning. The Kotlin port is ~25 lines, and each landmine is either
 *   impossible to write or a compile error. That asymmetry is the whole lesson.
 *
 *   P.S. Even the worst DANGER's bug class — `total.add(...)` with the result silently
 *   dropped — is now a compiler warning: see ex17 and the -Xreturn-value-checker flag
 *   it switches on in build.gradle.kts.
 *
 * DOCS & READING:
 *   https://kotlinlang.org/docs/comparison-to-java.html
 *   https://kotlinlang.org/docs/operator-overloading.html
 *   https://kotlinlang.org/docs/java-to-kotlin-idioms-strings.html
 *   https://kotlinlang.org/docs/java-to-kotlin-collections-guide.html
 *   https://kotlinlang.org/docs/java-to-kotlin-nullability-guide.html
 */
package ex16

import java.math.BigDecimal

// The entire data model — the port of Customer.java, LineItem.java, and Order.java
// (~150 lines): equals/hashCode/toString generated, no setters, defaults replace the
// telescoping constructors, `String?` replaces the "may be null" Javadoc.
data class Customer(val name: String, val email: String?, val vip: Boolean = false)
data class LineItem(val product: String, val quantity: Int, val unitPrice: BigDecimal)
data class Order(val id: Int, val customer: Customer, val items: List<LineItem>)

// The port of Payment.java and its three subclasses: sealed means the compiler KNOWS
// these are all the payments there are — see paymentMessage below.
sealed class Payment
data class Paid(val amount: BigDecimal) : Payment()
data class Refunded(val amount: BigDecimal, val reason: String) : Payment()
object Pending : Payment()

// Port of OrderUtils.lineTotal — but as an extension function [ex07]: item.lineTotal().
// The stdlib overloads BigDecimal arithmetic, so no .multiply() chain:
//   unitPrice * quantity.toBigDecimal()
// LineItem("Widget", 2, BigDecimal("5.00")).lineTotal() → 10.00
fun LineItem.lineTotal(): BigDecimal = unitPrice * quantity.toBigDecimal()

// Port of OrderUtils.grandTotal — the accumulator loop (with its forgotten-reassignment
// trap) becomes items.sumOf { }, which has a BigDecimal overload [ex08, ex09].
fun Order.grandTotal(): BigDecimal = items.sumOf { it.lineTotal() }

// Port of OrderUtils.contactLine — the if/else becomes one line, and unlike Java the
// compiler FORCES you to handle null [ex02, ex03, ex13].
// Email present → "Name <email-lowercased>", email null → "Name (no email)".
//   contactLine(Customer("Alice", "Alice@Example.COM")) → "Alice <alice@example.com>"
//   contactLine(Customer("Bob", null))                  → "Bob (no email)"
// Hint: customer.email?.let { ... } ?: "..."
// (There is no Kotlin port of contactLineCareless: it doesn't compile here.)
fun contactLine(customer: Customer): String =
    customer.email?.let { "${customer.name} <${it.lowercase()}>" } ?: "${customer.name} (no email)"

// Port of OrderUtils.paymentMessage — exhaustive `when` over the sealed class: no casts,
// no else, and a missing branch is a COMPILE error, not an IllegalStateException [ex05, ex11].
//   Paid(BigDecimal("49.99"))                    → "Paid 49.99"
//   Refunded(BigDecimal("12.50"), "damaged box") → "Refunded 12.50 (damaged box)"
//   Pending                                      → "Awaiting payment"
fun paymentMessage(payment: Payment): String = when (payment) {
    is Paid -> "Paid ${payment.amount}"
    is Refunded -> "Refunded ${payment.amount} (${payment.reason})"
    Pending -> "Awaiting payment"
}

// Port of the THREE receipt overloads + StringBuilder loop: defaults replace the
// overloads, templates + joinToString replace the appends [ex02, ex06, ex08].
// Append " (VIP)" to the first line when the customer is a VIP — `if` is an
// expression, use it inside the template.
// receipt(order1) where order1 = Order(1, alice(VIP), [2 x Widget @ 5.00, 1 x Gizmo @ 2.50]):
//   Order #1 for Alice (VIP)
//   2 x Widget = 10.00 EUR
//   1 x Gizmo = 2.50 EUR
//   Total: 12.50 EUR
//   Thank you!
// Hint: items.joinToString("\n") { ... } for the middle lines.
fun receipt(order: Order, currency: String = "EUR", footer: String = "Thank you!"): String {
    val header = "Order #${order.id} for ${order.customer.name}${if (order.customer.vip) " (VIP)" else ""}"
    val lines = order.items.joinToString("\n") { "${it.quantity} x ${it.product} = ${it.lineTotal()} $currency" }
    return "$header\n$lines\nTotal: ${order.grandTotal()} $currency\n$footer"
}

// Port of OrderUtils.bigSpenders — the groupingBy(reducing(ZERO, ..., ::add)) pipeline
// becomes groupBy + filter + sorted, and compareTo(minimum) >= 0 becomes plain >=
// (Kotlin maps comparison operators to compareTo, so scale never bites here) [ex09, ex14].
// Names of customers whose orders add up to at least `minimum`, sorted A→Z.
// One customer may have several orders — group first, then sum.
// Hint: orders.groupBy { it.customer.name }, then filter on the summed totals.
fun bigSpenders(orders: List<Order>, minimum: BigDecimal = BigDecimal("100")): List<String> =
    orders.groupBy { it.customer.name }
        .filterValues { customerOrders -> customerOrders.sumOf { it.grandTotal() } >= minimum }
        .keys
        .sorted()

// Port of OrderUtils.applyDiscount — but where the Java version mutates the order it
// was given (read its DANGER comment!), this returns a NEW order and the original
// CANNOT change: `val` + data class means the mutation bug is unwritable [ex04, ex09].
// Reduce every unit price by `percentOff` percent. BigDecimal etiquette: multiply
// first, divide by 100 last, so the quotient stays exact.
// Hint: order.copy(items = order.items.map {
//     it.copy(unitPrice = it.unitPrice * (100 - percentOff).toBigDecimal() / 100.toBigDecimal())
// })
fun withDiscount(order: Order, percentOff: Int = 10): Order =
    order.copy(items = order.items.map {
        it.copy(unitPrice = it.unitPrice * (100 - percentOff).toBigDecimal() / 100.toBigDecimal())
    })
